.phony:all
all:1_exception 2_exception 3_exception 4_exception

1_exception:1_exception.cpp
	g++-4.8 -std=c++11 -o $@ $^

2_exception:2_exception.cpp
	g++-4.8 -std=c++11 -o $@ $^

3_exception:3_exception.cpp
	g++-4.8 -std=c++11 -o $@ $^

4_exception:4_exception.cpp
	g++-4.8 -std=c++11 -o $@ $^

.phony:clean
clean:
	rm -rf 1_exception 2_exception 3_exception 4_exception
