.phony:all
all:1virtual_fun 2xiebian 3xigou_chongxie 4final 5override

1virtual_fun:1virtual_fun.cpp
	g++-4.8 -std=c++11 -o $@ $^

2xiebian:2xiebian.cpp
	g++-4.8 -std=c++11 -o $@ $^

3xigou_chongxie:3xigou_chongxie.cpp
	g++-4.8 -std=c++11 -o $@ $^

4final:4final.cpp
	g++-4.8 -std=c++11 -o $@ $^

5override:5override.cpp
	g++-4.8 -std=c++11 -o $@ $^

.phony:clean
clean:
	rm -rf 1virtual_fun 2xiebian 3xigou_chongxie 4final 5override
