.phony:all
all:1_unordered_map 2_unordered_multimap 3_unordered_set 4_unordered_multiset 5_repeatedNTimes 6_intersection 7_containsDuplicate 8_uncommonFromSentences

1_unordered_map:1_unordered_map.cpp
	g++-4.8 -std=c++11 -o $@ $^

2_unordered_multimap:2_unordered_multimap.cpp
	g++-4.8 -std=c++11 -o $@ $^

3_unordered_set:3_unordered_set.cpp
	g++-4.8 -std=c++11 -o $@ $^

4_unordered_multiset:4_unordered_multiset.cpp
	g++-4.8 -std=c++11 -o $@ $^

5_repeatedNTimes:5_repeatedNTimes.cpp
	g++-4.8 -std=c++11 -o $@ $^

6_intersection:6_intersection.cpp
	g++-4.8 -std=c++11 -o $@ $^

7_containsDuplicate:7_containsDuplicate.cpp
	g++-4.8 -std=c++11 -o $@ $^

8_uncommonFromSentences:8_uncommonFromSentences.cpp
	g++-4.8 -std=c++11 -o $@ $^

.phony:clean
clean:
	rm -rf 1_unordered_map 2_unordered_multimap 3_unordered_set 4_unordered_multiset 5_repeatedNTimes 6_intersection 7_containsDuplicate 8_uncommonFromSentences
