.phony:all
all:1inher 2inher 3inher NonInher friend_inher_test static_inher_test lingxing_inher_test lingxing_virtual_inher_test zuhe_inher_test

1inher:1inher.cpp
	g++-4.8 -std=c++11 -o $@ $^

2inher:2inher.cpp
	g++-4.8 -std=c++11 -o $@ $^

3inher:3inher.cpp
	g++-4.8 -std=c++11 -o $@ $^

NonInher:NonInher.cpp
	g++-4.8 -std=c++11 -o $@ $^

friend_inher_test:friend_inher_test.cpp
	g++-4.8 -std=c++11 -o $@ $^

static_inher_test:static_inher_test.cpp
	g++-4.8 -std=c++11 -o $@ $^

lingxing_inher_test:lingxing_inher_test.cpp
	g++-4.8 -std=c++11 -o $@ $^

lingxing_virtual_inher_test:lingxing_virtual_inher_test.cpp
	g++-4.8 -std=c++11 -o $@ $^

zuhe_inher_test:zuhe_inher_test.cpp
	g++-4.8 -std=c++11 -o $@ $^

.phony:clean
clean:
	rm -rf 1inher 2inher 3inher NonInher friend_inher_test static_inher_test lingxing_inher_test lingxing_virtual_inher_test zuhe_inher_test
