.PHONY:all
all:gouzaoVector iteratorVector capacityVector operVector iteratorQuestion test myVector

gouzaoVector:gouzaoVector.cpp
	g++-4.8 -std=c++11 -o $@ $^

iteratorVector:iteratorVector.cpp
	g++-4.8 -std=c++11 -o $@ $^

capacityVector:capacityVector.cpp
	g++-4.8 -std=c++11 -o $@ $^

operVector:operVector.cpp
	g++-4.8 -std=c++11 -o $@ $^

iteratorQuestion:iteratorQuestion.cpp
	g++-4.8 -std=c++11 -o $@ $^

test:test.cpp
	g++-4.8 -std=c++11 -o $@ $^

myVector:myVector.cpp
	g++-4.8 -std=c++11 -o $@ $^

.PHONY:clean
clean:
	rm -rf gouzaoVector iteratorVector capacityVector operVector iteratorQuestion test myVector
