.PHONY:all
all:gouzaoList iteratorList modifyList question test_deque

gouzaoList:gouzaoList.cpp
	g++-4.8 -std=c++11 -o $@ $^

iteratorList:iteratorList.cpp
	g++-4.8 -std=c++11 -o $@ $^

modifyList:modifyList.cpp
	g++-4.8 -std=c++11 -o $@ $^

question:question.cpp
	g++-4.8 -std=c++11 -o $@ $^

test_deque:test_deque.cpp
	g++-4.8 -std=c++11 -o $@ $^

.PHONY:clean
clean:
	rm -rf gouzaoList iteratorList modifyList question test_deque
